export interface IUser{
    "row_id": number,
    "ФИО": string,
    "Телефон": string,
    "Дата рождения": string,
    "Статус/Звание": string,
    "Город": string,
    "Учителя": string,
    "Вегетарианское питание": string,
    "Участие в концерте": string,
    "На машине": string,
    "Пожелания":string,
    "Дата регистрации":string,
    "Дата оплаты":string,
    "Сумма оплаты": string,
    "Количество оплат": string,
    "Координатор": string,
    "Доп питание": string,
    "Формат номера": string,
    "Будет видео?": string,
    "Длительность номера": string,
    "Тема номера": string,
    "Описание номера": string,
    "Общая сумма": string,
    "Время прибытия на станцию": string,
    "Информация по машине": string,
    "user_id": string
}
