name: pnpm Example Workflow
on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
            - name: Setup pages
              id: pages
              uses: actions/configure-pages@v3
            - name: Build with Jekyll
              uses: actions/jekyll-build-pages@v1
                with:
                source: ./
                destination: ./seminar-frontend
            - name: Upload GitHub Pages artifact
            uses: actions/upload-pages-artifact@v1s
    deploy:
        permissions:
        contents: read
        pages: write
        id-token: write
        runs-on: ubuntu-latest
        needs: jekyll-build
        environment:
        name: github-pages
        url: ${{steps.deployment.outputs.page_url}}
        steps:
        - name: Deploy artifact
            id: deployment
            uses: actions/deploy-pages@v1
