name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.1
              with:
                  version: latest
            - uses: actions/setup-node@v3
              with:
                  node-version: '20'
            - run: pnpm install
            - run: pnpm lint
            - run: pnpm build
